# Generated by Django 6.0.4 on 2026-04-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_promocodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
