# Generated by Django 6.0.4 on 2026-04-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_preferred_variant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_crypto',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='network',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('nowpayments', 'NOWPayments'), ('wallet', 'Wallet')], default='manual', max_length=24),
        ),
        migrations.AddField(
            model_name='purchase',
            name='provider_invoice_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('waiting', 'Waiting'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('create_failed', 'Create failed'), ('wallet_waiting', 'Wallet waiting'), ('wallet_confirmed', 'Wallet confirmed'), ('wallet_failed', 'Wallet failed'), ('wallet_rejected', 'Wallet rejected')], default='pending', max_length=32),
        ),
    ]
