# Generated by Django 6.0.4 on 2026-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_purchase_amount_crypto_purchase_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planaccess",
            name="generation_blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
