# Generated by Django 6.0.2 on 2026-04-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='request_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
